### ISSUE TITLE
Error: ENOENT: no such file or directory, open '.env'

### ISSUE THREAD

**Issue by hadeszs** [michzimny/learninglocker2-docker#9]
Hi Michał, I am learning to use your code and I got two issues. 
1.  when I run ./build-dev.sh. there are some errors: 
{ Error: ENOENT: no such file or directory, open '.env'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.config (/opt/learninglocker/node_modules/dotenv/lib/main.js:30:37)
    at /opt/learninglocker/node_modules/dotenv/config.js:10:25
    at Object.<anonymous> (/opt/learninglocker/node_modules/dotenv/config.js:11:3)
    at Module._compile (module.js:653:30)
    at Module._extensions..js (module.js:664:10)
    at Object.require.extensions.(anonymous function) [as .js] (/opt/learninglocker/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12) errno: -2, code: 'ENOENT', syscall: 'open', path: '.env' }
2. After I run docker-compose up -d
learninglocker2docker_nginx_1, learninglocker2docker_ui_1,learninglocker2docker_api_1 and learninglocker2docker_worker_1 were keep restarting loop.

Do you know how to fix this? thanks a lot.

**Comment by michzimny** [comment]
Hi @hadeszs,
re 1: yes, the errors appear however the images get properly built. The errors about missing configuration file that is not necessary when building the app.

Re 2: Did you proceeded as given in `README.md` (see blow)?
> BUT, for the first time, as Mongo requires some significant time to start up, you should rather: (...)
It should help when starting the services for the first time.

If not, then please check `docker-compose logs -f worker` to see what is the problem.

**Comment by hadeszs** [comment]
Hi @michzimny , thanks for the reply. 
Yes, I proceeded as given in the read me file. I looked into a looping container. 
The error is:  standard_init_linux.go:211: exec user process caused "no such file or directory"
Thanks a lot for the help.

**Comment by hadeszs** [comment]
In addition, I am using docker desktop on Window 10. Do I need to use dos2unix in the Dockerfile? thank you.

**Comment by jbeninson** [comment]
@hadeszs As you suggested with your previous comment, the problem is likely files with windows style line endings being executed within your linux containers. I forked this repo to add windows compatibility (it will checkout the files with the appropriate line endings though dos2unix would also work). I was also seeing an issue with Mongo using the Windows bind mounts so I made a named_volumes version of the docker-compose file. I was planning on making a PR: https://github.com/jbeninson/learninglocker2-docker

Give it a whirl and let me know if it works for ya.
